export const data = [
  {
    Title: "Sports",
    Subtitle: "1 Transaction",
    Icon: require("../assets/icons/Active.svg"),
    Amount: "5899.00",
    Percentage: "65%",
  },
  {
    Title: "Shopping",
    Subtitle: "13 Transactions",
    Icon: require("../assets/icons/limit.svg"),
    children: null,
    Amount: "1366.00",
    Percentage: "15%",
  },
  {
    Title: "Restaurants",
    Subtitle: "17 Transactions",
    Icon: require("../assets/icons/manage.svg"),
    children: null,
    Amount: "799.00",
    Percentage: "9%",
  },
  {
    Title: "Groceries",
    Subtitle: "9 Transactions",
    Icon: require("../assets/icons/Lock.svg"),
    children: null,
    Amount: "527.55",
    Percentage: "6%",
  },
  {
    Title: "Bills & Utilities",
    Subtitle: "3 Transactions",
    Icon: require("../assets/icons/airplane.svg"),
    children: null,
    Amount: "456.55",
    Percentage: "5%",
  },
];
